apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-canary
  namespace: robokart
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-canary
  minReplicas: 4
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75